#!/bin/sh

RELEASE=1.3-beta.12

cd modules-runtime-hot
meteor publish --release $RELEASE
cd ../hot
meteor publish --release $RELEASE
cd ../babel-compiler-hot
meteor publish --release $RELEASE
cd ../ecmascript-hot
meteor publish --release $RELEASE
