#!/bin/sh

RELEASE=1.3-rc.2

cd modules-runtime-hot
meteor publish --release $RELEASE
cd ../hot
meteor publish --release $RELEASE
cd ../babel-compiler-hot
meteor publish --release $RELEASE
cd ../ecmascript-hot
meteor publish --release $RELEASE
