#!/bin/sh
. ./last-upstream-commit

cd ~/www/meteor.gadicc
git diff $LAST_COMMIT HEAD -- packages/babel-compiler packages/ecmascript packages/modules-runtime/ | filterdiff -x \*npm-shrinkwrap.json | colordiff | less -R
